In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
import warnings
warnings.filterwarnings("ignore")

### Load the dataset

In [50]:
data=pd.read_csv('F:/ict/titanic_dataset (1).csv')

In [51]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [52]:
data.shape

(891, 12)

### Preprocessing the Data

In [53]:
#Drop Unnecessary Columns
data = data.drop(['PassengerId','Name','Ticket','Cabin','Embarked'], axis=1)

In [54]:
#Handling Missing Values
data['Age'].fillna(data['Age'].mean(), inplace=True)

In [55]:
# Convert categorical data to numerical data
data=pd.get_dummies(data)

In [56]:
data.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male
0         0       3  22.0      1      0   7.2500           0         1
1         1       1  38.0      1      0  71.2833           1         0
2         1       3  26.0      0      0   7.9250           1         0
3         1       1  35.0      1      0  53.1000           1         0
4         0       3  35.0      0      0   8.0500           0         1

In [57]:
data.isna().sum()

Survived      0
Pclass        0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_female    0
Sex_male      0
dtype: int64

In [58]:
#divide our data into independent feature and dependent feature or target feature
x = data.drop('Survived', axis=1)
y = data['Survived']

In [59]:
#divide the data set into train and test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

### KNN Model

In [60]:
from sklearn.neighbors import KNeighborsClassifier

In [61]:
from sklearn.metrics import accuracy_score

In [62]:
metric_k=[]
neighbors = np.arange(3,15)

In [63]:
  for k in neighbors:
    classifier = KNeighborsClassifier(n_neighbors=k, metric= 'euclidean')
    classifier.fit(x_train,y_train)
    y_pred_knn = classifier.predict(x_test)
    acc = accuracy_score(y_test,y_pred_knn)
    metric_k.append(acc)

In [64]:
metric_k

[0.6871508379888268,
 0.7039106145251397,
 0.6927374301675978,
 0.7094972067039106,
 0.7094972067039106,
 0.6927374301675978,
 0.7094972067039106,
 0.6927374301675978,
 0.7150837988826816,
 0.7094972067039106,
 0.7430167597765364,
 0.7150837988826816]

In [65]:
plt.plot(neighbors,metric_k,'o-')
plt.xlabel("K value")
plt.ylabel("Accuracy")
plt.grid()

In [66]:
classifier = KNeighborsClassifier(n_neighbors=13, metric= 'euclidean')
classifier.fit(x_train,y_train)
y_pred_knn = classifier.predict(x_test)
acc = accuracy_score(y_test,y_pred_knn)

In [67]:
accuracy_score(y_test,y_pred_knn)

0.7430167597765364

In [68]:
#Another way to find Accuracy
KNN_Model=classifier.fit(x_train,y_train)

In [69]:
Score_KNN = KNN_Model.score(x_test,y_test)

In [70]:
Score_KNN

0.7430167597765364

### K Fold Cross Validation

In [71]:
from sklearn.model_selection import KFold
kfold_validator = KFold(10)

In [72]:
for train_index, test_index in kfold_validator.split(x,y):
    print('Training Index: ',train_index)
    print('Validation Index: ',test_index)

Training Index:  [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 3

In [73]:
from sklearn.model_selection import cross_val_score
cv_result = cross_val_score(KNN_Model,x,y,cv= kfold_validator)

In [74]:
cv_result

array([0.64444444, 0.64044944, 0.6741573 , 0.71910112, 0.6741573 ,
       0.71910112, 0.66292135, 0.74157303, 0.76404494, 0.76404494])

In [75]:
#take average accuracy
np.mean(cv_result)

0.7003995006242197

### Stratified Cross Validation

In [76]:
from sklearn.model_selection import StratifiedKFold
skfold_validator = StratifiedKFold(n_splits = 10)

In [77]:
for train_index, test_index in skfold_validator.split(x,y):
    print('Training Index: ',train_index)
    print('Validation Index: ',test_index)

Training Index:  [ 82  84  85  88  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 3

In [78]:
skcv_result = cross_val_score(KNN_Model,x,y,cv= skfold_validator)

In [79]:
skcv_result

array([0.65555556, 0.62921348, 0.64044944, 0.76404494, 0.6741573 ,
       0.69662921, 0.70786517, 0.74157303, 0.73033708, 0.74157303])

In [80]:
#take average accuracy
np.mean(skcv_result)

0.698139825218477

### SVM Model

In [81]:
from sklearn.svm import SVC

In [82]:
svm_clf = SVC(kernel='rbf')

In [83]:
SVM_Model=svm_clf.fit(x_train,y_train)

In [84]:
SVM_Model

SVC()

In [85]:
y_pred = svm_clf.predict(x_test)

In [86]:
accuracy_score(y_test,y_pred)

0.659217877094972

In [87]:
#Another way to find accuracy
Score_SVM = SVM_Model.score(x_test,y_test)

In [88]:
Score_SVM

0.659217877094972

### K Fold Cross Validation

In [89]:
from sklearn.model_selection import cross_val_score
kf_result = cross_val_score(SVM_Model,x,y,cv= kfold_validator)

In [90]:
kf_result

array([0.6       , 0.6741573 , 0.66292135, 0.6741573 , 0.66292135,
       0.70786517, 0.65168539, 0.74157303, 0.73033708, 0.69662921])

In [91]:
#take average accuracy
np.mean(kf_result)

0.6802247191011237

### Stratified Cross Validation

In [92]:
skf_result = cross_val_score(SVM_Model,x,y,cv= skfold_validator)

In [93]:
skf_result

array([0.62222222, 0.57303371, 0.68539326, 0.74157303, 0.69662921,
       0.70786517, 0.68539326, 0.71910112, 0.70786517, 0.6741573 ])

In [94]:
#take average accuracy
np.mean(skf_result)

0.6813233458177278